/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LookAtMeRouteImport } from './routes/look-at-me'
import { Route as LogoDropsRouteImport } from './routes/logo-drops'
import { Route as CirclePackingRouteImport } from './routes/circle-packing'
import { Route as IndexRouteImport } from './routes/index'

const LookAtMeRoute = LookAtMeRouteImport.update({
  id: '/look-at-me',
  path: '/look-at-me',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoDropsRoute = LogoDropsRouteImport.update({
  id: '/logo-drops',
  path: '/logo-drops',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclePackingRoute = CirclePackingRouteImport.update({
  id: '/circle-packing',
  path: '/circle-packing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circle-packing': typeof CirclePackingRoute
  '/logo-drops': typeof LogoDropsRoute
  '/look-at-me': typeof LookAtMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circle-packing': typeof CirclePackingRoute
  '/logo-drops': typeof LogoDropsRoute
  '/look-at-me': typeof LookAtMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circle-packing': typeof CirclePackingRoute
  '/logo-drops': typeof LogoDropsRoute
  '/look-at-me': typeof LookAtMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/circle-packing' | '/logo-drops' | '/look-at-me'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/circle-packing' | '/logo-drops' | '/look-at-me'
  id: '__root__' | '/' | '/circle-packing' | '/logo-drops' | '/look-at-me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CirclePackingRoute: typeof CirclePackingRoute
  LogoDropsRoute: typeof LogoDropsRoute
  LookAtMeRoute: typeof LookAtMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/look-at-me': {
      id: '/look-at-me'
      path: '/look-at-me'
      fullPath: '/look-at-me'
      preLoaderRoute: typeof LookAtMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-drops': {
      id: '/logo-drops'
      path: '/logo-drops'
      fullPath: '/logo-drops'
      preLoaderRoute: typeof LogoDropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle-packing': {
      id: '/circle-packing'
      path: '/circle-packing'
      fullPath: '/circle-packing'
      preLoaderRoute: typeof CirclePackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CirclePackingRoute: CirclePackingRoute,
  LogoDropsRoute: LogoDropsRoute,
  LookAtMeRoute: LookAtMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
